services:
  # Backend service (not exposed to the host)
  backend:
    build:
      context: ./backend
    container_name: backend
    # No ports exposed to the host
    expose:
      - "5000" # Expose the backend's internal port
    # Frontend service
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80" # Expose the frontend to the host
